---
title: "Weekly update for July 6"
date: "July 2017"
output: 
    rmdshower::shower_presentation:
        ratio: 4x3
---
# Show and Tell <br> July 6

## NIST Technical Colloquium on the Weight of Evidence  
- Keynote speakers (Ian Evett & Christophe Champod, UNIL)  
- Panel discussions on: 
    - What is the weight of evidence?
    - How do we quantify the weight of evidence?
    - Validation and inter-laboratory testing
    - Reliability, Reproducibility, and Repeatability
    - Population Statistics (controversial!)
    - Method Evaluation
    - Communicating results of analyzing forensic evidence

## NIST Technical Colloquium - major takeaways 
- Big focus on the Likelihood Ratio approach to quantifying the weight of evidence
    - There was discussion about whether it should be 'Bayes Factor' instead
    - We were sad that score-based LR's were not more popular...  
- CSAFE Reading Group / Working Group  
    - Coming Fall 2017 ?!?! 
    - There is a LOT of important articles/books on this subject matter  
    
## OPPTAG Preparations  
- What is OPPTAG? 
    - A week-long 'camp' for talented and gifted students about forensics
    - Making a mock crime scene and having students analyze different pieces of evidence  
    - Visiting the Ankeny Crime Lab
    - ISU Campus Police talk: processing a crime scene and collecting evidence
    - Brandon Garret, U.V.: how evidence would hold up in court, how lawyers use results  
    
## REU Updates 

- Students are working on projects! 
    * Guillermo & Martin (shoes) 
    * Dr Newman & Stephanie (steganograpy)
- Chat & Chew #2 tomorrow
    * students posting their updates on [GitHub](https://github.com/CSAFE-ISU/REU-welcome)
- Haven't started with any handwriting or bullet data collection
    * email the students at [csafe-reu@iastate.edu](mailto:csafe-reu@iastate.edu)
- Visit to Iowa DCI Criminialistics Laboratory on Tuesday, July 11th
    
## Human Factors 

- Amazon Mechanical Turk survey ready to go
    * (just waiting on @heike's final approval and a funding source)
    * If you want to take the survey and haven't yet, email Sam ([sctyner@iastate.edu](mailto:sctyner@iastate.edu))
    
## Sam has a crazy idea

[ROpenSci Fellowship](https://ropensci.org/blog/blog/2017/07/06/ropensci-fellowships)

Idea: Apply for this funding to write an online book for Open Forensic Science in R